name = "pw-vault-api"
main = "worker/index.js"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

# Account ID (uncomment if needed)
# account_id = "c2d12008eaa79cc26054336a7fe3d9c0"

[vars]
ALLOWED_ORIGIN = "https://vault.mdlo.dev"

[[d1_databases]]
binding = "DB"
database_name = "pw-vault-db"
database_id = "ede7411b-cbe6-4098-a8ff-41376d53088c"
