name = "pw-vault-api"
main = "index.js"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[vars]
ALLOWED_ORIGIN = "https://vault.mdlo.dev"

[[d1_databases]]
binding = "DB"
database_name = "pw-vault-db"
database_id = "ede7411b-cbe6-4098-a8ff-41376d53088c"
